databases:
  - name: postgres
    databaseName: task_manager
    user: task_manager
    region: frankfurt
    plan: free
    postgresMajorVersion: 13
    ipAllowList: []

services:
  - type: web
    name: task_manager
    region: frankfurt
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: ROLLBAR_RAILS_ACCESS_TOKEN
        sync: false
      - key: NEWRELIC_LICENSE_KEY
        sync: false
      - key: COVERALLS_TASKMANAGER_TOKEN
        sync: false
      - key: MAILER_USERNAME
        sync: false
      - key: MAILER_PASSWORD
        sync: false
      - key: MAILER_ADDRESS
        sync: false
      - key: MAILER_DOMAIN
        sync: false
      - key: MAILER_PORT
        value: 587
      - key: MAILER_AUTHENTICATION
        value: plain
