databases:
  - name: postgres
    region: frankfurt
    plan: free
    postgresMajorVersion: 11

services:
  - type: web
    name: task_manager
    region: frankfurt
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: ROLLBAR_RAILS_ACCESS_TOKEN
        sync: false
      - key: NEWRELIC_LICENSE_KEY
        sync: false