# Application services
password_reset:
  TOKEN_EXPIRATION_TIME: <%= 1.day %>
# Services access TOKENs
services:
  COVERALLS_TASKMANAGER_TOKEN : <%= ENV['COVERALLS_TASKMANAGER_TOKEN']%>
  ROLLBAR_RAILS_ACCESS_TOKEN : <%= ENV['ROLLBAR_RAILS_ACCESS_TOKEN']%>
  NEWRELIC_LICENSE_KEY : <%= ENV['NEWRELIC_LICENSE_KEY']%>
# Mailer and SMTP settings
mailer:
  MAILER_USERNAME : <%= ENV['MAILER_USERNAME']%>
  MAILER_PASSWORD : <%= ENV['MAILER_PASSWORD']%>
  MAILER_ADDRESS : <%= ENV['MAILER_ADDRESS']%>
  MAILER_DOMAIN : <%= ENV['MAILER_DOMAIN']%>
  MAILER_HOST : <%= ENV['MAILER_HOST']%>
  MAILER_PORT : <%= ENV['MAILER_PORT']%>
  MAILER_AUTHENTICATION : <%= ENV['MAILER_AUTHENTICATION']%>
  DEFAULT_NO_REPLY_EMAIL: <%= ENV['DEFAULT_NO_REPLY_EMAIL']%>
# Rails private keys
rails_keys:
  RAILS_MASTER_KEY : <%= ENV['RAILS_MASTER_KEY']%>